"My vim configuration file


"Set the mapleader
let mapleader =" "

"Enusre the use of vimrc
set nocompatible


"Set line numbers to exist and be relative
set number relativenumber
set encoding=utf-8

"Enable autocompletion
set wildmode=longest,list,full

"When searching for string make it highlighted
set hlsearch

"Enable syntax highlighting and filetype recognition
filetype plugin on
syntax on

set tabstop=8
set softtabstop=0 
set expandtab 
set shiftwidth=4 
set smarttab


"Disalble automatic newline commenting
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Splits open at the bottom and right, which is non-retarded, unlike vim defaults.
set splitbelow splitright

" Compile document, be it groff/LaTeX/markdown/etc.
map <leader>c :w! \| !compiler "%:p"<CR>

" Open corresponding .pdf/.html or preview
map <leader>p :!opout "%:p"<CR>

" Runs a script that cleans out tex build files whenever I close out of a .tex file.
autocmd VimLeave *.tex !texclear %
